import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { InterFont } from "@/lib/font";
import { Toaster } from "react-hot-toast";


export const metadata = {
  title: "Tiles Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${InterFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster position="top-right" />
        <Navbar></Navbar>
        <main>
          {children}
        </main>
        <Footer></Footer>
        </body>

    </html>
  );
}
